[tool.poetry]
name = "pychatteringy"
version = "0.1.0"
description = ""
authors = ["CWKevo <<>>"]

[tool.poetry.dependencies]
python = "^3.6"
fuzzywuzzy = "^0.18.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
